// Limpia la salida de `delombok` (quita anotaciones/imports propios de Lombok
// y simplifica nombres totalmente calificados) y reemplaza los archivos originales.
const fs = require("fs");
const path = require("path");

const SRC_DIR = "C:/Users/cabasaury/AppData/Local/Temp/delombok_out";
const DEST_DIR = path.resolve(__dirname, "..", "src", "main", "java", "coviello", "gestion_de_alumnos", "model");

const files = fs.readdirSync(SRC_DIR).filter(f => f.endsWith(".java"));
let changed = 0;

for (const file of files) {
  const destPath = path.join(DEST_DIR, file);
  if (!fs.existsSync(destPath)) {
    console.warn(`AVISO: no existe destino para ${file}, se omite.`);
    continue;
  }

  let content = fs.readFileSync(path.join(SRC_DIR, file), "utf-8");

  const lines = content.split(/\r?\n/);
  const out = [];
  for (const line of lines) {
    const t = line.trim();
    if (t.startsWith("// Generated by delombok")) continue;
    if (t === '@java.lang.SuppressWarnings("all")') continue;
    if (t === "@lombok.Generated") continue;
    if (t.startsWith("import lombok.")) continue;
    out.push(line);
  }
  content = out.join("\n");

  content = content
    .replace(/@java\.lang\.Override/g, "@Override")
    .replace(/\bjava\.lang\.Object\b/g, "Object")
    .replace(/\bjava\.lang\.String\b/g, "String")
    .replace(/\n{3,}/g, "\n\n"); // colapsar líneas en blanco duplicadas

  if (!content.endsWith("\n")) content += "\n";

  fs.writeFileSync(destPath, content, "utf-8");
  changed++;
}

console.log(`Archivos de modelo actualizados: ${changed}/${files.length}`);
